[deps]
ConicQKD = "89930fff-1c97-468e-be5c-77ab6ddad2d9"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Ket = "412c778c-4733-41d8-b706-9e072557ba34"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[sources]
ConicQKD = {url = "https://github.com/araujoms/ConicQKD.jl"}

[compat]
ConicQKD = "0.2 - 0.3"
Dualization = "0.5.9 - 0.7"
Hypatia = "0.9"
JuMP = "1.26"
Ket = "0.5.1 - 0.8"
MosekTools = "0.15"
Optim = "1.13"
julia = "1.11"
